import type { Cottage } from "./types";

export const cottageDemoData: Cottage[] = [
  {
    id: "cot-1",
    propertyId: "prop-1",
    name: "Riverfront Villa",
    code: "RV-01",
    slug: "riverfront-villa",
    category: "Premium",
    shortDescription: "Spacious cottage with private deck and river view.",
    fullDescription: "Ideal for families and couples who want a serene setting with comfort.",
    amenities: ["King Bed", "Private Deck", "Air Conditioning", "Wi-Fi"],
    basePrice: 190,
    weekendPrice: 220,
    coverImage: "/demo/cottages/riverfront-cover.jpg",
    galleryImages: ["/demo/cottages/riverfront-1.jpg", "/demo/cottages/riverfront-2.jpg"],
    maxGuests: 4,
    status: "active",
  },
  {
    id: "cot-2",
    propertyId: "prop-1",
    name: "Garden Nest",
    code: "GN-02",
    slug: "garden-nest",
    category: "Standard",
    shortDescription: "Cozy cottage surrounded by tropical greenery.",
    fullDescription: "Comfortable and practical option for short to medium stays.",
    amenities: ["Queen Bed", "Mini Fridge", "Garden Patio"],
    basePrice: 120,
    weekendPrice: 145,
    coverImage: "/demo/cottages/garden-cover.jpg",
    galleryImages: ["/demo/cottages/garden-1.jpg"],
    maxGuests: 2,
    status: "draft",
  },
];
