import { z } from "zod";

export const cottageSchema = z.object({
  property_id: z.string().uuid(),
  code: z.string().min(1),
  name: z.string().min(2),
  slug: z.string().min(2),
  category: z.string().min(2),
  short_description: z.string().optional(),
  full_description: z.string().optional(),
  bed_type: z.string().optional(),
  max_adults: z.number().int().min(1),
  max_children: z.number().int().min(0),
  max_infants: z.number().int().min(0),
  max_total_guests: z.number().int().min(1),
  room_count: z.number().int().min(1),
  has_ac: z.boolean().default(false),
  breakfast_included: z.boolean().default(true),
  extra_bed_allowed: z.boolean().default(false),
  is_combined_unit: z.boolean().default(false),
  component_codes: z.array(z.string()).default([]),
  amenities: z.array(z.string()).default([]),
  weekday_price: z.number().nonnegative(),
  weekend_price: z.number().nonnegative(),
  child_price: z.number().nonnegative(),
  extra_bed_price: z.number().nonnegative(),
  pricing_note: z.string().optional(),
  cover_image: z.string().optional(),
  gallery_images: z.array(z.string()).default([]),
  sort_order: z.number().int().default(0),
  is_featured: z.boolean().default(false),
  is_bookable: z.boolean().default(true),
  status: z.enum(["active", "inactive", "maintenance"]),
});

export type CottageInput = z.infer<typeof cottageSchema>;
