import { AdminPageHeader } from "@/components/admin/shared/AdminPageHeader";
import { ReportSummaryCards } from "@/features/admin/reports/components/ReportSummaryCards";
import { ReportTableClient } from "@/features/admin/reports/components/ReportTableClient";
import { ReportsNav } from "@/features/admin/reports/components/ReportsNav";
import { getReportDataset } from "@/features/admin/reports/services/reports.service";
import { resolveReportDateRange } from "@/features/admin/reports/services/reports-params";
import { safeDivide } from "@/features/admin/reports/reports.utils";

export default async function BookingSourcesReportPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { from, to } = await resolveReportDateRange(searchParams);
  const ds = await getReportDataset(from, to);
  const rows = Object.entries(ds.bookings.reduce<Record<string,{count:number;confirmed:number;pending:number;cancelled:number;revenue:number;collection:number;out:number;nights:number}>>((a,b)=>{const s=b.source||"other";if(!a[s])a[s]={count:0,confirmed:0,pending:0,cancelled:0,revenue:0,collection:0,out:0,nights:0};a[s].count++;if(["confirmed","advance_paid","checked_in","checked_out","completed"].includes(b.status))a[s].confirmed++;if(["pending","new_request","contacted"].includes(b.status))a[s].pending++;if(["cancelled","rejected","no_show"].includes(b.status))a[s].cancelled++;a[s].revenue+=b.finalAmount;a[s].collection+=b.paidAmount;a[s].out+=b.outstandingAmount;a[s].nights+=b.nights;return a;},{})).map(([source,v])=>({id:source,source,totalBookings:v.count,confirmedBookings:v.confirmed,pendingBookings:v.pending,cancelledBookings:v.cancelled,totalRevenue:v.revenue,totalCollection:v.collection,outstandingAmount:v.out,averageBookingValue:safeDivide(v.revenue,v.count),averageStayDuration:safeDivide(v.nights,v.count)}));
  return <div className="space-y-4"><AdminPageHeader title="Booking Sources Report" description="Source performance for marketing and channel focus decisions." /><ReportsNav />
  <ReportSummaryCards cards={[{label:"Best Source by Revenue",value:[...rows].sort((a,b)=>b.totalRevenue-a.totalRevenue)[0]?.source??"—"},{label:"Best by Confirmed",value:[...rows].sort((a,b)=>b.confirmedBookings-a.confirmedBookings)[0]?.source??"—"},{label:"Highest Cancellation",value:[...rows].sort((a,b)=>b.cancelledBookings-a.cancelledBookings)[0]?.source??"—"},{label:"Highest Outstanding",value:[...rows].sort((a,b)=>b.outstandingAmount-a.outstandingAmount)[0]?.source??"—"},{label:"Manual vs Website",value:`${rows.filter((r)=>r.source!=="website").reduce((s,r)=>s+r.totalBookings,0)} / ${rows.find((r)=>r.source==="website")?.totalBookings ?? 0}`}]} />
  <ReportTableClient title="Source-wise bookings" fileName="booking-sources-report.csv" rows={rows} searchKeys={["source"]} columns={[{key:"source",label:"Source"},{key:"totalBookings",label:"Bookings",sortable:true},{key:"confirmedBookings",label:"Confirmed",sortable:true},{key:"pendingBookings",label:"Pending",sortable:true},{key:"cancelledBookings",label:"Cancelled",sortable:true},{key:"totalRevenue",label:"Revenue",sortable:true,format: "currency_inr"},{key:"totalCollection",label:"Collection",format: "currency_inr"},{key:"outstandingAmount",label:"Outstanding",format: "currency_inr"},{key:"averageBookingValue",label:"Avg Value",format: "currency_inr"},{key:"averageStayDuration",label:"Avg Stay",format: "nights_1"}]} />
  </div>;
}
